import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";
import {
  Box,
  Avatar,
  Text,
  Heading,
  Stack,
  Image,
  Flex,
  Link,
  Tag,
  StatArrow,
  StatHelpText,
  Stat,
  Button,
  Divider,
} from "@chakra-ui/react";
import NextLink from "next/link";
import { FaCircle } from "react-icons/fa";
import { Row, Col } from "react-bootstrap";
import ArticleItem from "../components/ArticleItem";
import ProductSlider from "../components/ProductSlider";

export default function Auction() {
  const images = [
    // "/girl-with-basket.png",
    // "/peace-of-mind.png",
    "/style.png",
    "/arthur.png",
    "/after-war.png",
    "/sisters.png",
    "/useless.png",
    "/chubby.png",
    "/four-children.png",

    "/better-days.png",
  ];

  return (
    <div>
      <Head>
        <title>Auction | Artsplit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Box as="main" py={10} className={styles.container}>
        <Flex align={"center"} gap={2}>
          <FaCircle style={{ color: "#BF702A" }} />
          <Heading as={"h1"} fontSize="lg" color="#6B6968">
            Auction
          </Heading>
        </Flex>
        <section>
          <Stack direction={["column", "row"]} columnGap={20} py={10}>
            <Box flex={1}>
              <ProductSlider images={[]} />
            </Box>
            <Box flex={1}>
              <Box pb={2} mb={2}>
                <Heading fontSize={"large"} mt={5}>
                  <NextLink href={"/auction"} passHref>
                    <Link>Dreams in Reality</Link>
                  </NextLink>
                </Heading>
              </Box>
              <Flex alignItems={"center"} gap={3}>
                <Avatar
                  src="/el-anatsui-potrait.png"
                  size={"sm"}
                  name="el-anatsui"
                />
                <Text color="#6B6968">El Anatsui, 1996</Text>
              </Flex>
              <Image src="/graph.png" alt="" />
              <Flex
                // justify={"space-between"}
                align="center"
                borderTopStyle="dashed"
                borderTopWidth={1}
                gap={4}
                py={3}
              >
                <Text flex={1}>$1,500</Text>
                <Box flex={1}>
                  <Tag variant={"outline"}>5 units</Tag>
                </Box>
                <Stat flex={1}>
                  <StatHelpText>
                    <StatArrow type="decrease" />
                    50%
                  </StatHelpText>
                </Stat>
              </Flex>
              <Flex
                // justify={"space-between"}
                align="center"
                gap={4}
                py={[1, 3]}
              >
                <Box
                  flex={1}
                  borderWidth={1}
                  py={[2, 2, 2, 3]}
                  pl={3}
                  borderRadius="lg"
                >
                  <Text fontSize={"xs"}>Starting Bid</Text>
                  <Text color="black" fontWeight={"semibold"}>
                    $500.00
                  </Text>
                </Box>
                <Box
                  flex={1}
                  borderWidth={1}
                  py={[2, 2, 2, 3]}
                  pl={3}
                  borderRadius="lg"
                  bg="black"
                >
                  <Text fontSize={"xs"} color="white">
                    Highest Bid
                  </Text>
                  <Text color="white" fontWeight={"extrabold"}>
                    $3,983.00
                  </Text>
                </Box>
              </Flex>
              <Flex justify={"space-between"} gap={5} mt={5}>
                <Button variant={"outline"} borderRadius={"2xl"}>
                  View Item
                </Button>
                <Button
                  borderRadius={"2xl"}
                  flex={1}
                  style={{
                    background: "#BF702A",
                    borderColor: "#bf702a",
                    color: "#fff",
                  }}
                >
                  Place bid
                </Button>
              </Flex>
            </Box>
          </Stack>
        </section>
        <Box as="section" mt={5}>
          <Stack direction={["column", "row"]} gap={10}>
            <Box flex={1}>
              <Heading size={"sm"} mb={5}>
                Art Info
              </Heading>
              <Box overflowY="scroll" h={"64"} pr={5}>
                <Text as="p" mb={4}>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Aperiam, aut! Fuga maxime, labore ea, perspiciatis, tempora
                  exercitationem quis enim aut doloribus accusantium nihil sed
                  unde quisquam veritatis cum corrupti quod. Lorem ipsum dolor
                  sit amet consectetur adipisicing elit. Aperiam, aut! Fuga
                  maxime, labore ea, perspiciatis, tempora exercitationem quis
                  enim aut doloribus accusantium nihil sed unde quisquam
                  veritatis cum corrupti quod.
                </Text>
                <Text as="p">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Aperiam, aut! Fuga maxime, labore ea, perspiciatis, tempora
                  exercitationem quis enim aut doloribus accusantium nihil sed
                  unde quisquam veritatis cum corrupti quod. Lorem ipsum dolor
                  sit amet consectetur adipisicing elit. Aperiam, aut! Fuga
                  maxime, labore ea, perspiciatis, tempora exercitationem quis
                  enim aut doloribus accusantium nihil sed unde quisquam
                  veritatis cum corrupti quod.
                </Text>
              </Box>
            </Box>
            <Box flex={1}>
              <Heading size={"sm"} mb={5}>
                Live Bids
              </Heading>
              <Divider />
              <Box
                h="64"
                display={"flex"}
                flexDir="column"
                flexWrap="nowrap"
                overflowY={"auto"}
                pr={5}
                pt={5}
              >
                {Array(5)
                  .fill("a")
                  .map((item) => (
                    <Flex
                      key={item}
                      alignItems={"center"}
                      justify="space-between"
                      mt={2}
                      mb={4}
                    >
                      <Flex gap={3} alignItems={"center"}>
                        <Avatar
                          src="/el-anatsui-potrait.png"
                          size={["sm", "sm", "sm", "md"]}
                          name="el-anatsui"
                        />
                        <div>
                          <Text fontSize={"xs"}>John Gray Doe</Text>
                          <Text color="#6B6968" fontSize={"xs"}>
                            El Anatsui, 1996
                          </Text>
                        </div>
                      </Flex>

                      <Tag variant={"outline"} size={["sm", "sm", "sm", "md"]}>
                        9 Units
                      </Tag>
                      <Text
                        fontWeight={"semibold"}
                        fontSize={["xs", "xs", "xs", "sm"]}
                      >
                        $5,000.00
                      </Text>
                    </Flex>
                  ))}
              </Box>
            </Box>
          </Stack>
        </Box>

        <Box as="section" py={10}>
          <Flex justify={"space-between"} align="center">
            <Text fontSize="xl" fontWeight={"semibold"}>
              Explore other artworks
            </Text>

            <NextLink href="/explore" passHref>
              <Link color="#A6A6A6">See all</Link>
            </NextLink>
          </Flex>
          <Box as={Row} py={10}>
            {images.map((item) => (
              <ArticleItem link="/auction" item={item} key={item} />
            ))}
          </Box>
        </Box>
      </Box>

      <Footer />
    </div>
  );
}
