import {
  Box,
  Accordion,
  Text,
  Input,
} from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";
import { Row, Col } from "react-bootstrap";
import { useState, useMemo } from "react";
import { QUESTIONS } from "../Constants";
import FAQ from "components/FAQ";

const Faq: NextPage = () => {
  const items = QUESTIONS;

  const [query, setQuery] = useState("");

  const q = useMemo(
    () => items.filter((f) => f?.q.includes(query)),
    [items, query]
  );

  return (
    <div>
      <div>
        <Head>
          <title>FAQ | Artsplit</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />

        <main>
          <Box
            height={"300px"}
            backgroundImage="url('/contact-bg.png')"
            backgroundSize={"cover"}
            backgroundPosition="center"
            backgroundRepeat="no-repeat"
            alignItems={"center"}
          >
            <Box as={Row} className="justify-content-center" pt={"28"}>
              <Box as={Col} xs={10} sm={10} md={6}>
                <Text
                  align={"center"}
                  color="#ffffff"
                  className={styles.faqTitle}
                >
                  Frequently Asked Questions
                </Text>
                <Input
                  variant="filled"
                  placeholder="Search"
                  onChange={(t) => setQuery(t.target?.value)}
                  height={14}
                  bgColor="white"
                  rounded="xl"
                  outline={0}
                  _focus={{
                    backgroundColor: '#FFFFFF'
                  }}
                />
              </Box>
            </Box>
          </Box>

          <section className={styles.container} style={{ marginTop: "2rem" }}>
            <Row className="justify-content-center">
              <Col xs={12} sm={10} md={8}>
                <Accordion allowToggle>
                  { q.map((item, i) => <FAQ key={`faq-${i}`} index={i} faq={item} />) }
                </Accordion>
              </Col>
            </Row>
          </section>
        </main>
      </div>
      <Footer />
    </div>
  );
};

export default Faq;
