import type { NextPage } from "next";
import { Box } from "@chakra-ui/react";
import Head from "next/head";
import Footer from "components/Footer";
import Header from "components/Header";
import styles from "styles/UserManual.module.css";
const PrivacyPolicy: NextPage = () => {
  return (
    <div>
      <Head>
        <title>User Manual | Artsplit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Box as="main" mb={[32, 32, 0, 0]} className="page-container">
        <h1
          style={{
            fontSize: 30,
            fontWeight: 500,
            marginBottom: 20,
            marginTop: 20,
            textAlign: "center",
          }}
        >
          User Manual
        </h1>

        <h1 className={styles.h1}>Table Of Contents</h1>
        <h2 className={styles.h2}>Introduction</h2>
        <ul className={styles.ul}>
          <li>PURPOSE OF THIS USER GUIDE</li>
          <li>WHAT IS ARTSPLIT?</li>
          <li>WHAT IS THE ARTSPLIT APP?</li>
          <li>WHY ARTSPLIT?</li>
        </ul>

        <h2 className={styles.h2}>Products</h2>
        <ul className={styles.ul}>
          <li>SPLIT CONTRACT</li>
          <li>LEASE CONTRACT</li>
          <li>IMAGE RIGHTS</li>
        </ul>

        <h2 className={styles.h2}>Terms</h2>
        <ul className={styles.ul}>
          <li>User</li>
          <li>Primary Market</li>
          <li>Secondary Market</li>
          <li>Listings</li>
          <li>Market Price</li>
          <li>Splits</li>
          <li>Portfolio</li>
          <li>Wallet</li>
        </ul>

        <h2 className={styles.h2}>App features</h2>
        <ul className={styles.ul}>
          <li>KEY THINGS YOU CAN DO ON THE APP</li>
          <li>LOADING AND WITHDRAWAL OF FUNDS</li>
          <li>THE SOCIAL FEATURE</li>
          <li>HOW TO GET ON THE APP</li>
        </ul>

        <h2 className={styles.h2}>Help and Support</h2>
        <ul className={styles.ul}>
          <li>SPLIT CONTRACT</li>
          <li>Lease Contract</li>
          <li>Image Rights</li>
        </ul>

        <hr className={styles.divider} />

        <h3 className={styles.h3}>Introduction</h3>
        <h4 className={styles.h4}>Purpose of the USER GUIDE</h4>
        <p className={styles.p}>
          This user guide aims to introduce our unique model of art acquisition,
          trading, re-trading, and collecting, to first time art buyers and
          distinguished art patrons.
        </p>

        <h4 className={styles.h4}>What is ARTSPLIT?</h4>
        <p className={styles.p}>
          ARTSPLIT is an art trading technology company that makes it possible
          to buy into investment grade African art. We are on a mission to
          introduce African art as a currency, making it more accessible to
          invest, trade and collect, with as little as $10.
        </p>

        <h4 className={styles.h4}>What is the ARTSPLIT APP?</h4>
        <p className={styles.p}>
          The ARTSPLIT app is an art trading and social platform. It is an
          interactive space that provides users with access to sign-up and
          participate in live auctions, bids, trades, portfolio management as
          well as access to invest and lease African artworks. The app also
          provides such social engagements functions as community building
          amongst users.
        </p>

        <h4 className={styles.h4}>Why ARTSPLIT?</h4>
        <p className={styles.p}>
          ARTSPLIT is a business with a primary focus on elevating the stature
          of African art in the global art market. We believe the African artist
          has the power and capacity to inform and direct the value of their
          works. However, we are democratizing the access to investment grade
          artworks through the purchase of full or shared ownership of artworks
          through leasing, as well as trading.
        </p>

        <h3 className={styles.h3}>Products</h3>
        <h4 className={styles.h4}>Split contracts</h4>
        <p className={styles.p}>
          A split contract is ARTSPLIT’s process of taking the current value of
          a piece of art and breaking it up into 100,000 units. These units
          (also known as “splits”) are put up for auction to enable the
          co-ownership of that artwork. The owner of the artwork can determine
          the percentage of ownership they would want to put up for auction.
          However, the minimum percentage that can be put up on the ARTSPLIT app
          is 10% (i.e 10,000 units).
        </p>

        <h4 className={styles.h4}>Lease contract</h4>
        <p className={styles.p}>
          As a result of the split contract, the lease contract becomes
          necessary. When 10 or 20 people now own an artwork, it brings up the
          question, where would the artwork sit? The lease contract makes it
          possible for physical custodianship of an artwork. It means a user can
          bid to have the artwork seating on his/her wall. If the user win’s the
          bid, based on the eligibility criteria of having that artwork and any
          other insurance conditions, that artwork would be transported to the
          winner of the bid. The artwork would be in the bid winner’s custody
          for the specified period of time.
        </p>

        <h4 className={styles.h4}>Image Rights</h4>
        <p className={styles.p}>
          An image right is the Intellectual Property (IP) of an image. ARTSPLIT
          would be responsible for getting the image rights of the most priced
          African artworks by master artists. People would be able to bid for
          these IP and when they do, they can decide to hold on to it, re-trade
          it in the secondary market and can also make commercial decisions that
          are independent of ARTSPLIT. 5 All of the bids that happen in the
          primary market can all move to the secondary market for re-trading and
          portfolio asset management based on the discretion of the owners.
        </p>

        <h3 className={styles.h3}>Terms</h3>
        <h4 className={styles.h4}>User</h4>
        <p className={styles.p}>
          A user is anyone engaging with the ARTSPLIT app for business and
          social purposes. This individual would have completed a sign-up
          process and must have received a blue verification tick and the
          completion of the profile registration process.
        </p>
        <h4 className={styles.h4}>Primary Market</h4>
        <p className={styles.p}>
          The primary market is where ARTSPLIT opens an auction and introduces
          artworks and image rights on the ARTSPLIT platform to all its users.
          The users would have the ability to place bids on these
          offerings/artworks.
        </p>
        <p className={styles.p}>
          Artworks and image rights listed on ARTSPLIT go through a timed
          bidding process through which ownership is transferred to one or more
          users.
        </p>
        <p className={styles.p}>
          The highest bidder pays to own the work either in splits (in the case
          of split contract) for a specified period (in the case of lease
          contract) or permanently (in the case of Image rights). The bid
          duration can be between 5 to 10 days.
        </p>

        <p className={styles.p}>
          For split contracts, a minimum of 10% (10,000 units) out of 100%
          (100,000 units) of splits of the artwork is put up in the primary
          market for auction/bidding, while the remaining 90% remains with the
          owner of the artwork who put it up for listing. The primary market
          therefore refers to the activities around the auction process.
        </p>

        <h3 className={styles.h3}>Secondary market</h3>
        <p className={styles.p}>
          The secondary market is the trading section on ARTSPLIT that allows
          users easily transfer ownership (split contracts) of artworks they
          have won in the primary market (during the bidding/auction process) to
          other users who are willing to own them. It takes place after auctions
          are concluded from the primary market. ARTSPLIT transfers the artwork
          to the (splits) portfolio of winner(s) of the bid who then can
          re-trade or sell it to other users on the ARTSPLIT platform whenever
          they want and at whatever price they want and/or for the highest
          available price that is on the market as defined by potential buyer
          (s) or bid (s) or bidder (s).
        </p>

        <p className={styles.p}>
          All the bids that happen in the primary market can all move to the
          secondary market for re-trading and portfolio asset management based
          on the discretion of the owners.
        </p>

        <p className={styles.p}>
          The secondary market is the free market where owners can trade and
          re-trade all the assets within their portfolio whether it is the
          units, the lease, or the image rights.
        </p>

        <h4 className={styles.h4}>LIsting</h4>
        <p className={styles.p}>
          This is a process of onboarding a new artwork onto the ARTSPLIT
          platform for auction on the primary market. This could either be for
          split contract auctions or Image rights.
        </p>

        <p className={styles.p}>
          There are two ways a user can list an artwork on ARTSPLIT’s platform.
          This is through uploading your entire artwork for sale (which would be
          quantified as 100k units/splits) or alternatively uploading for sale a
          portion of the artwork (a minimum of 10% will be required or a sum of
          10k units/splits).
        </p>

        <p className={styles.p}>
          These sales go directly to the primary market where bidders will
          procure splits and acquire split contract/s for the portions/ units/
          splits owned by buyer. Another way to list for is the sale of 7
          legitimately owned Intellectual Property (IP) of Image Rights, this
          refers to the sale of the digital image right/s– see more details
          below.
        </p>

        <p className={styles.p}>
          Note that the listing process, requirements and their related terms
          and conditions, differ for each listing type.
        </p>

        <p className={styles.p}>
          After a user submits a listing request, ARTSPLIT will verify ownership
          of the artwork via several acceptable standard checks and balances,
          including but not limited to provenance checks. ARTSPLIT will arrange
          for pick-up of physical artworks and logistics and processing fees
          charged to the user are non-refundable. If the request for listing is
          successful, a timed auction is created on the platform. A bid for
          ownership by other users or potential buyers commences.
        </p>

        <h4 className={styles.h4}>Market Price</h4>
        <p className={styles.p}>
          This is a term used in the secondary market to represent the last
          known value of an artwork on the ARTSPLIT app. This is the last price
          that the artwork was last sold on the platform.
        </p>

        <p className={styles.p}>
          When an artwork is listed on ARTSPLIT for the first time and auctioned
          in the primary market, the market price of the artwork will be
          determined at the end of the bidding by:
        </p>

        <ul className={styles.ul}>
          <li>
            Multiplying each users bid amount by their desired number of units
            to get total amount spent by the user,
          </li>
          <li>
            Adding up all total amounts spent by each user who has won the bid
            to get a cumulative total amount bided for the artwork
          </li>
          <li>
            Dividing this cumulative amount by the total number of units won in
            the bidding process for that artwork to get the market price.,
          </li>
        </ul>

        <p className={styles.p}>
          The market price determined above will then form the current value of
          a unit of the artwork when traded in the secondary market.
        </p>

        <p className={styles.p}>
          However, if the artwork is already traded in the secondary market,
          then the market price of the artwork becomes the last price at which a
          seller sold a unit of the artwork to a buyer.
        </p>

        <p className={styles.p}>
          This value fluctuates relative to the forces of demand and supply in
          the secondary market and determines the total value of a user’s
          portfolio.
        </p>

        <h4 className={styles.h4}>SPLITS (ALSO KNOWN AS UNITS)</h4>
        <p className={styles.p}>
          This term is used by ARTSPLIT to represent a fraction of an artwork,
          which can be owned by a user through auction or trade and is managed
          as an asset within their portfolio.
        </p>

        <p className={styles.p}>
          A piece of investment grade art listed is divided into 100,000 splits
          (units) and the minimum percentage of ownership that can be listed is
          10% (10,000 Splits).
        </p>

        <ul className={styles.ul}>
          <li>
            Owned units refer to the total number of units of an artwork a user
            current owns.
          </li>
          <li>
            Available units represent the total number of units put up for sale
            by different people who currently own units of the artwork.
          </li>
        </ul>

        <h4 className={styles.h4}>PORTFOLIO</h4>
        <p className={styles.p}>
          This is a representation of a user’s assets on the ARTSPLIT platform.
          Artworks that users own in ARTSPLIT are recorded here and their value
          is determined by the market price of each artwork. Hence, the value is
          subject to fluctuation based on trading activities in the secondary
          market.
        </p>

        <h4 className={styles.h4}>Wallet</h4>
        <p className={styles.p}>
          This refers to a user’s available funds in the ARTSPLIT ecosystem. It
          reflects cash deposits and withdrawal activities of a user on the 9
          ARTSPLIT platform. While cash deposits go into the user’s wallet, cash
          withdrawals, platform fees, bid amounts and trade amounts are taken
          from the user’s wallet. There are limits tied to user’s wallet for
          both deposits and withdrawals, and these limits are determined by
          users KYC level.
        </p>

        <h3 className={styles.h3}>App Features</h3>
        <h4 className={styles.h4}>KEY THINGS YOU CAN DO ON THE APP</h4>
        <p className={styles.p}>
          The app enables a user bid, trade, follow and engage with other users
          and artists.
        </p>
        <p className={styles.p}>
          The ARTSPLIT app has many other functions such as:
        </p>
        <ul className={styles.ul}>
          <li>Ability to create a profile and upload a display picture.</li>
          <li>Funding your account through credit or debit cards.</li>
          <li>Quick conversion of local currency for funding wallet</li>
          <li>Uploading own artworks into a personal catalogue.</li>
          <li>Management of portfolio from profile.</li>
          <li>Verification of updates and status updates.</li>
        </ul>

        <h4 className={styles.h4}>LOADING AND WITHDRAWAL OF FUNDS</h4>
        <p className={styles.p}>
          The currency for the ARTSPLIT app is the US dollars ($). Users can
          purchase and perform their transaction from the app by funding their
          account. If a user wants to withdraw down from app fund, they can do
          so using one of these five currencies –US Dollars, GBP, Euros, Cedis
          and Naira.
        </p>

        <p className={styles.p}>
          A user in the US, England, Europe, Ghana or Nigeria can withdraw down
          from their app fund in these countries into their local currency
          account. However, if a user is not in any of these countries, the user
          10 will need to withdraw into a domiciliary account that reflects any
          of the five currencies above.
        </p>

        <h4 className={styles.h4}>The Social Feature</h4>
        <p className={styles.p}>
          The timeline feature allows users to to post, like and comment on
          other users posts that are shared on the app. In upcoming iteration,
          users will be able to share artworks that are on live auctions or
          upcoming auctions unto their timeline, like and comment on articles
          and general updates from ARTSPLIT. Also on the app, a user can follow
          other users, creating an art community. Users can also follow artist.
        </p>

        <h4 className={styles.h4}>HOW TO GET ON THE APP</h4>
        <h4 className={styles.h4}>Installation</h4>
        <p className={styles.p}>For Android Devices</p>
        <ul className={styles.ul}>
          <li>
            Search for ARTSPLIT in the Google Play Store. Install the
            application.
          </li>
        </ul>

        <p className={styles.p}>For Apple Devices</p>
        <ul className={styles.ul}>
          <li>
            Search for ARTSPLIT in the Apple Store. Install the application
          </li>
        </ul>

        <p className={styles.p}>For Web Browsers</p>
        <ul className={styles.ul}>
          <li>
            Visit <a href="https://artsplit.com">https://artsplit.com</a>
          </li>
        </ul>

        <h4 className={styles.h4}>SIGNUP & LOGIN</h4>
        <p className={styles.p}>
          For a new user, click the “Sign Up” link to complete the process. On
          the “Create Account” page, insert your information, including your
          email and desired password or you can use the single sign-on option to
          login with a Google or Facebook account.
        </p>

        <p className={styles.p}>
          You will be prompted to verify your email if you did not sign-up using
          the single sign-on feature on the app. All new users will be prompted
          to verify their phone number by inserting the OTP (one time password)
          sent via message to the selected number used for registration.
        </p>

        <p className={styles.p}>
          Alternatively, mobile users who have signed into the app before can
          consequently use their biometrics for future sign-in attempts.
        </p>

        <h3 className={styles.h3}>HELP & SUPPORT</h3>
        <p className={styles.p}>
          You can connect with a customer representative through the help and
          support tab under account setting in the app or on the support tab on
          the website.
        </p>
        <ul className={styles.ul}>
          <li>
            <strong>
              For more information about ARTSPLIT, you can connect with us by
            </strong>
          </li>
          <li>
            Sending an email to{" "}
            <a href="mailto:support@artsplit.com">support@artsplit.com</a>
          </li>
          <li>
            Calling us on <a href="tel:+2349088962169">+2349088962169</a>
          </li>
        </ul>
      </Box>
      <Footer />
    </div>
  );
};

export default PrivacyPolicy;
